apiVersion: v1
kind: Pod
metadata:
  namespace: rucio
  name: rucio-db-init
spec:
  containers:
  - name: rucio-db-init
    image: rucio/rucio-init:latest
    env:
    - name: RUCIO_CFG_DATABASE_DEFAULT
      value: "postgresql://rubin:<not-tellin>@usdf-rucio-rw.rucio-db.svc.cluster.local:5432/rucio"
    - name: RUCIO_CFG_BOOTSTRAP_X509_EMAIL
      value: "bjwhite@fnal.gov"
    - name: RUCIO_CFG_BOOTSTRAP_X509_IDENTITY
      value: "/DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Brandon White/CN=UID:bjwhite"
